### ISSUE TITLE
Subtasks for milestones

### ISSUE THREAD

**Issue by isc-fsanches** [diashenrique/npm-iris#8]
Considering the new updates, system is considering tasks as milestones. 
It can be a problem with the "duration" field. In general, when duration=0, project software consider it a milestone.

![Screen Shot 2020-09-25 at 2 46 09 PM](https://user-images.githubusercontent.com/55411699/94304634-dd5a6c00-ff3d-11ea-8993-49010099ba60.png)

**Comment by diashenrique** [comment]
The reason it's because the milestone icon it's showed when the start DateTime and end DateTime are the same. I'm changing the property StartDate and DueDate from %Date to %DateTime to taking into consideration the estimation in hours.
