### ISSUE TITLE
Installation ZPM error outside of docker container

### ISSUE THREAD

**Issue by SergeyMi37** [diashenrique/npm-iris#9]
zmp "install npm-iris"
[npm-iris]      Reload START
[npm-iris]      Reload SUCCESS
[npm-iris]      Module object refreshed.
[npm-iris]      Validate START
[npm-iris]      Validate SUCCESS
[npm-iris]      Compile START
[npm-iris]      Compile SUCCESS
[npm-iris]      Activate START
[npm-iris]      Configure START
[npm-iris]      Configure FAILURE - ERROR #5001: Error copying directory /opt2/isc/iris20201/mgr/.modules/NPMIRIS/npm-iris/0.1.4/src/csp/ to /opt/irisapp/csp/
  > ERROR #320: Create failed because: /opt/irisapp/csp/
[npm-iris]      Activate FAILURE - ERROR #5001: Error copying directory /opt2/isc/iris20201/mgr/.modules/NPMIRIS/npm-iris/0.1.4/src/csp/ to /opt/irisapp/csp/
  > ERROR #320: Create failed because: /opt/irisapp/csp/
ERROR #5001: Error copying directory /opt2/isc/iris20201/mgr/.modules/NPMIRIS/npm-iris/0.1.4/src/csp/ to /opt/irisapp/csp/
  > ERROR #320: Create failed because: /opt/irisapp/csp/
ERROR #5001: Error copying directory /opt2/isc/iris20201/mgr/.modules/NPMIRIS/npm-iris/0.1.4/src/csp/ to /opt/irisapp/csp/
  > ERROR #320: Create failed because: /opt/irisapp/csp/

**Comment by SergeyMi37** [comment]
The module in docker is already installed. Installing with the ZPM package makes sense when installing on another instance.
 IMHO.

**Comment by SergeyMi37** [comment]
Sorry, I didn't understand that this is a joke

**Comment by diashenrique** [comment]
Hi @SergeyMi37 

Could you share wich ZPM version you are using?

Dmitry and Evgeny also installed the package using zpm. Both of them with success.

I'm using zpm 0.2.5.

**Comment by SergeyMi37** [comment]
i am using ZPM version 0.2.7.
As far as I know, Dmitry and Eugene installed in the docker. I installed outside of docker.

**Comment by SergeyMi37** [comment]
I managed to install it on Windows. Thanks, it works.

**Comment by diashenrique** [comment]
> i am using ZPM version 0.2.7.
> As far as I know, Dmitry and Eugene installed in the docker. I installed outside of docker.

Ah, it's true. Sorry to forget that.

**Comment by diashenrique** [comment]
> I managed to install it on Windows. Thanks, it works.

I'm glad to read that. Thank you for your interesting

**Comment by SergeyMi37** [comment]
When installing the application, I suggest using not an absolute path /opt/irisapp/csp/, but a relative one ${cspdir}/npm

**Comment by SergeyMi37** [comment]
https://github.com/diashenrique/npm-iris/pull/10
